### ISSUE TITLE
feature request, create a direct lake semantic model in a different workspace

### ISSUE THREAD

**Issue by djouallah** [m-kovalsky/Fabric#1]
currently, it seems, fct.create_blank_semantic_model(newDatasetName) by default uses the workspace where the lakehouse is located, it will be nice to have an option to create the semantic model in a different workspace.

**Comment by m-kovalsky** [comment]
This function, has the following parameters. The workspace defaults to the workspace where the notebook is located but you can set it. You can also set the compatibility level. In fact, all the functions in the .whl file have the ability to set the workspace. Make sure to do help(functionname) to find out the parameters and more info on a particular function.

create_blank_semantic_model(datasetName, compatibilityLevel = 1604, workspaceName = None)

**Comment by djouallah** [comment]
it seems The workspace defaults to the lakehouse location not the where the notebook is located
