### ISSUE TITLE
Workaround to fix DateTime data type

### ISSUE THREAD

**Issue by TK-Fab** [m-kovalsky/Fabric#5]
![2](https://github.com/user-attachments/assets/a2254b5e-cef8-4a75-b505-33c3f921342b)
Dear Michael,
Do you have any advise to what we can do to workaround the Datetime data type not-support issues ?  Truly appreciated your thoughts.

**Comment by m-kovalsky** [comment]
Have the relationships based on an integer column (YYYYMMDD format) - 20241001.
________________________________
From: TK-Fab ***@***.***>
Sent: Tuesday, October 1, 2024 6:37:23 AM
To: m-kovalsky/Fabric ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [m-kovalsky/Fabric] Workaround to fix DateTime data type (Issue #5)


2.png (view on web)<https://github.com/user-attachments/assets/a2254b5e-cef8-4a75-b505-33c3f921342b>
Dear Michael,
Do you have any advise to what we can do to workaround the Datetime data type not-support issues ? Truly appreciated your thoughts.

**Comment by TK-Fab** [comment]
Thank you so much

**Comment by TK-Fab** [comment]
Thanks Michael - it works
